name: Vulnerability scan

on: [push, pull_request]

jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: debricked/actions/security-scanning@v0.12.0
        with:
          token: ${{ secrets.DEBRICKED_TOKEN }}
